# Generated by Django 5.2.3 on 2025-07-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_badges_productcolors_productsizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='customer_type',
            field=models.CharField(choices=[('Retail', 'Retail'), ('Wholesale', 'Wholesale'), ('VIP', 'VIP')], default='Retail', max_length=20),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
