# Generated by Django 5.2.3 on 2025-07-09 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_customeruser_address_customeruser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='profile_pic',
        ),
    ]
