# Generated by Django 5.2.3 on 2025-07-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_remove_customeruser_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='customer_type',
        ),
    ]
