# Generated by Django 5.2.3 on 2025-07-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_remove_customeruser_city_remove_customeruser_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceConfigures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('small_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file_content', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
