# Generated by Django 5.2.3 on 2025-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_interfaceconfigures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceconfigures',
            name='file_content',
        ),
        migrations.AddField(
            model_name='interfaceconfigures',
            name='media_content',
            field=models.FileField(blank=True, null=True, upload_to='homepage_media/'),
        ),
        migrations.AddField(
            model_name='interfaceconfigures',
            name='media_type',
            field=models.CharField(choices=[('1', 'Image'), ('2', 'Video')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
