# Generated by Django 5.2.3 on 2025-07-10 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0009_remove_interfaceconfigures_created_at_and_more'),
        ('products', '0010_remove_productvarient_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceconfigures',
            name='best_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_product_configs', to='products.products'),
        ),
        migrations.AddField(
            model_name='interfaceconfigures',
            name='collection_media_content',
            field=models.FileField(default=1, upload_to='interface_media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interfaceconfigures',
            name='collection_media_type',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interfaceconfigures',
            name='collection_title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interfaceconfigures',
            name='hot_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hot_product_configs', to='products.products'),
        ),
        migrations.AddField(
            model_name='interfaceconfigures',
            name='new_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_product_configs', to='products.products'),
        ),
        migrations.AlterField(
            model_name='interfaceconfigures',
            name='small_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interfaceconfigures',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
