# Generated by Django 5.2.3 on 2025-07-10 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_interfaceconfigures_best_product_and_more'),
        ('products', '0010_remove_productvarient_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('media_type', models.IntegerField()),
                ('media_content', models.FileField(upload_to='interface_media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='interfaceconfigures',
            name='best_product',
        ),
        migrations.RemoveField(
            model_name='interfaceconfigures',
            name='collection_media_content',
        ),
        migrations.RemoveField(
            model_name='interfaceconfigures',
            name='collection_media_type',
        ),
        migrations.RemoveField(
            model_name='interfaceconfigures',
            name='collection_title',
        ),
        migrations.RemoveField(
            model_name='interfaceconfigures',
            name='hot_product',
        ),
        migrations.RemoveField(
            model_name='interfaceconfigures',
            name='new_product',
        ),
        migrations.CreateModel(
            name='InterfaceBests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_product_configs', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceHots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hot_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hot_product_configs', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_product_configs', to='products.products')),
            ],
        ),
    ]
