# Generated by Django 5.2.3 on 2025-07-10 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_interfacebests_created_at_and_more'),
        ('products', '0010_remove_productvarient_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('instagram_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_product_configs', to='products.products')),
            ],
        ),
    ]
