# Generated by Django 5.2.3 on 2025-07-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_interfaceinstagram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaceinstagram',
            name='instagram_product',
        ),
        migrations.AddField(
            model_name='interfaceinstagram',
            name='media_content',
            field=models.FileField(default=1, upload_to='interface_media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interfaceinstagram',
            name='media_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
