# Generated by Django 5.2.3 on 2025-07-06 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='subcategories',
            name='thumbnail',
        ),
    ]
