# Generated by Django 5.2.3 on 2025-07-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_categories_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_active',
            field=models.IntegerField(),
        ),
    ]
