# Generated by Django 5.2.3 on 2025-07-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productabout',
            name='title_details',
            field=models.CharField(default='Default Title', max_length=255),
        ),
    ]
