# Generated by Django 5.2.3 on 2025-07-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productabout_title_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productabout',
            name='title_details',
            field=models.CharField(max_length=255),
        ),
    ]
