# Generated by Django 5.2.3 on 2025-07-08 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productabout_title_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productabout',
            old_name='title_details',
            new_name='about_details',
        ),
    ]
