# Generated by Django 5.2.3 on 2025-07-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_title_details_productabout_about_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='description',
        ),
    ]
