# Generated by Django 5.2.3 on 2025-07-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_categories_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='url_slug',
        ),
    ]
