# Generated by Django 5.2.3 on 2025-07-09 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_badges_productcolors_productsizes'),
        ('products', '0008_remove_categories_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvarient',
            name='badge_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboards.badges'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvarient',
            name='color_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboards.productcolors'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvarient',
            name='size_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboards.productsizes'),
            preserve_default=False,
        ),
    ]
